apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cnd4y0uoq-go 
  janus-idp.io/tekton: cnd4y0uoq-go
  backstage.io/kubernetes-id: cnd4y0uoq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cnd4y0uoq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  