apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cnd4y0uoq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnd4y0uoq-go 
  name: cnd4y0uoq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cnd4y0uoq-go 
